---
slug: :mikutter-osc-kansai-2015
depends:
  mikutter: 3.0.0
  plugin:
  - gui
  - gtk
version: '0.0.6'
author: 
name: mikutter osc kansai support 2015
description: OSC kansai 2015のセミナースケジュールを表示するだけだと思った？
